sudo: false

language: node_js

branches:
  only:
    - master

env:
  - CXX=g++-4.8

node_js:
  - "8"
  - "7"
  - "6"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

before_script:
  - npm install

script:
  - npm run lint
  - npm run coverage
  - npm run coveralls
